core/core/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

# Api Documentation
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Todo API",
        default_version="v1",
        description="This is an api for Todo Application",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mjz589.2018@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("todo.urls")),
    path("api-auth/", include("rest_framework.urls")),
    # Api Documentation
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    re_path(r"^robots\.txt", include("robots.urls")),
    re_path(
        r"^ckeditor/", include("ckeditor_uploader.urls")
    ),  # The CKEditor path
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/todo/api/v1/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path
from . import views

app_name = "api-v1"

router = DefaultRouter()
router.register("task", views.TaskModelViewSet, basename="task")
urlpatterns = router.urls
urlpatterns += [
    path("weather/", views.WeatherView.as_view(), name="weather"),
]

"""
from django.urls import path
urlpatterns = [
    # path("task/", views.taskList, name="task-list"),
    path("task/", views.TaskList.as_view(), name="task-list"),
    # path("task/<int:id>/", views.taskDetail, name="task-detail"),
    path("task/<int:pk>/", views.TaskDetail.as_view(), name="task-detail"),
]
urlpatterns += router.urls
"""

core/todo/urls.py
from django.urls import path, include
from .views import (
    TaskList,
    TaskCreate,
    TaskComplete,
    TaskUpdate,
    TaskDelete,
    Weather,
)

app_name = "todo"

urlpatterns = [
    path("", TaskList.as_view(), name="task_list"),
    path("create-task/", TaskCreate.as_view(), name="create_task"),
    path("update-task/<int:pk>/", TaskUpdate.as_view(), name="update_task"),
    path(
        "complete-task/<int:pk>/",
        TaskComplete.as_view(),
        name="complete_task",
    ),
    path("delete-task/<int:pk>/", TaskDelete.as_view(), name="delete_task"),
    path("weather/", Weather.as_view(), name="weather"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models

# from django.contrib.auth.models import User
from django.urls import reverse


# from accounts.models import Profile
# from django.contrib.auth import get_user_model
# --- getting user model object ---
# User = get_user_model()


# Create your models here.


# user comes from accounts.Profile
class Task(models.Model):
    user = models.ForeignKey(
        "accounts.Profile", on_delete=models.CASCADE, null=True, blank=True
    )
    title = models.CharField(max_length=255)
    complete = models.BooleanField(default=False)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_api_url(self):
        return reverse("todo:api-v1:task-detail", kwargs={"pk": self.pk})

    class Meta:
        order_with_respect_to = "user"

core/todo/forms.py
from django import forms
from .models import Task


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("title",)


class UpdateTaskForm(forms.ModelForm):
    title = forms.CharField(max_length=255)

    class Meta:
        model = Task
        fields = ("title",)

core/todo/api/v1/views.py
from rest_framework.response import Response
from .serializers import TaskSerializer
from ...models import Task

# or instead of ...models you can point models.py like this: todo.models
from accounts.models import Profile

# class-based views for api
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework import serializers

# from .permissions import IsOwnerOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from .paginations import DefaultPagination

# caching
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_headers  # vary_on_cookie,
import requests
from decouple import config


class TaskModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = TaskSerializer
    # filters
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = [
        "complete",
    ]
    search_fields = [
        "title",
    ]
    ordering_fields = ["created_date"]
    # pagination
    pagination_class = DefaultPagination

    """ --- we used another method for user providing ---
    def perform_create(self, serializer):
        # user must automatically be provided and not be written by users
        profile = Profile.objects.get(user=self.request.user.id)
        serializer.save(user=profile) """

    def get_queryset(self):
        # define the queryset wanted
        if self.request.user.is_verified:
            profile = Profile.objects.get(user=self.request.user.id)
            queryset = Task.objects.filter(user=profile.id)
        else:
            raise serializers.ValidationError(
                {"detail": "User is not verified."}
            )
        return queryset

    # extra actions
    @action(
        methods=[
            "GET",
        ],
        detail=False,
    )
    def get_ok(self, request):
        return Response({"detail": "extra actions -OK-"})


class WeatherView(APIView):
    # With auth: cache requested url for each user for 20 minutes
    @method_decorator(cache_page(60 * 20))
    @method_decorator(
        vary_on_headers(
            "Authorization",
        )
    )
    def get(self, request, format=None):
        api_key = config(
            "openweather_apikey", default="18f933ce846bc85b1007e70e217290fe"
        )
        response = requests.get(
            f"https://api.openweathermap.org/data/2.5/weather?lat=37.474806&lon=57.315210&appid={api_key}"
        )
        data = response.json()
        # convert from kelvin to celsius with 0.01 rounding
        data["main"]["temp"] = round(data["main"]["temp"] - 273.15, 2)
        data["main"]["feels_like"] = round(
            data["main"]["feels_like"] - 273.15, 2
        )
        data["main"]["temp_min"] = round(data["main"]["temp_min"] - 273.15, 2)
        data["main"]["temp_max"] = round(data["main"]["temp_max"] - 273.15, 2)
        content = {"weather": data}
        return Response(content)

core/todo/views.py
from django.shortcuts import redirect
from django.views.generic import (
    View,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin

# weather
import requests
from django.core.cache import cache
from decouple import config

from django.urls import reverse_lazy
from .models import Task
from .forms import CreateTaskForm, UpdateTaskForm
from accounts.models import Profile
from core.celery import delete_completed_tasks

# Create your views here.


# show todo list ../todo/task_list.html
class TaskList(LoginRequiredMixin, ListView):
    model = Task
    template_name = "todo/task_list.html"
    context_object_name = "tasks"
    delete_completed_tasks.delay()

    def get_queryset(self):
        profile = Profile.objects.get(user=self.request.user)
        return self.model.objects.filter(user=profile)

    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super(TaskList, self).get_context_data(**kwargs)
        if not context.get("is_paginated", False):
            return context
        # Custom Pagination
        paginator = context.get("paginator")
        num_pages = paginator.num_pages
        current_page = context.get("page_obj")
        page_no = current_page.number

        if num_pages <= 5 or page_no <= 3:  # case 1 and 2
            pages = [x for x in range(1, min(num_pages + 1, 5))]
        elif page_no > num_pages - 3:  # case 4
            pages = [x for x in range(num_pages - 4, num_pages + 1)]
        else:  # case 3
            pages = [x for x in range(page_no - 2, page_no + 3)]

        # previous page and first page
        if page_no == 1:
            previous_page = 1
            first_page = 1
        else:
            previous_page = pages[page_no - 1] - 1
            first_page = pages[0]

        # next page and last page
        if page_no == pages[-1]:
            next_page = page_no
            last_page = 1
        else:  # page_no ==1  , pages[page_no] == 2 , pages[page_no] +1 = 3
            next_page = pages[page_no - 1] + 1
            last_page = pages[-1]
        page_count = len(pages)
        context.update(
            {
                "pages": pages,
                "first_page": first_page,
                "last_page": last_page,
                "previous_page": previous_page,
                "next_page": next_page,
                "current_page": page_no,
                "page_count": page_count,
            }
        )
        return context


# create a task ../todo/task_form.html
class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    form_class = CreateTaskForm
    success_url = reverse_lazy("todo:task_list")
    template_name = "todo/task_list.html"

    # automatically detect author
    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        form.instance.user = profile
        return super().form_valid(form)


# update/edit a task ../todo/task_update.html
class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "todo/task_update.html"
    success_url = reverse_lazy("todo:task_list")
    form_class = UpdateTaskForm

    # automatically detect author
    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        form.instance.user = profile
        return super().form_valid(form)


# delete  a task ../todo/task_confirm_delete.html
class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = "task"
    success_url = reverse_lazy("todo:task_list")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_queryset(self):
        profile = Profile.objects.get(user=self.request.user)
        return self.model.objects.filter(user=profile)


# mark a task as completed
class TaskComplete(LoginRequiredMixin, View):
    model = Task
    success_url = reverse_lazy("todo:task_list")
    context_object_name = "task"

    def get(self, request, *args, **kwargs):
        task = Task.objects.get(id=kwargs.get("pk"))
        task.complete = True
        task.save()
        return redirect(self.success_url)


# weathering widget
class Weather(LoginRequiredMixin, ListView):
    success_url = reverse_lazy("todo:task_list")
    context_object_name = "weather_api"
    template_name = "todo/weather.html"

    def get_queryset(self, *args, **kwargs):
        if cache.get("weather") is None:
            api_key = config(
                "openweather_apikey",
                default="18f933ce846bc85b1007e70e217290fe",
            )
            response = requests.get(
                f"https://api.openweathermap.org/data/2.5/weather?lat=37.474806&lon=57.315210&appid={api_key}"
            )
            data = response.json()
            # convert from kelvin to celsius with 0.01 rounding
            data["main"]["temp"] = round(data["main"]["temp"] - 273.15, 2)
            data["main"]["feels_like"] = round(
                data["main"]["feels_like"] - 273.15, 2
            )
            data["main"]["temp_min"] = round(
                data["main"]["temp_min"] - 273.15, 2
            )
            data["main"]["temp_max"] = round(
                data["main"]["temp_max"] - 273.15, 2
            )
            cache.set("weather", data)
        return cache.get("weather")

core/templates/todo/task_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

<!-- <title>  -->
{% block title %} Todo List {% endblock %}
<!-- <extra css>-->
{% block extra_css %}{% endblock %}

<!-- <body> -->
{% block content %}


<body class="body">
    <div class="container">
        <div class="today"></div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3">
                <div class="add-control">
                    <div class="form-group has-feedback">
                        <form method="POST">
                            {% csrf_token %}

                            <div class="todo-list"> <h3>"Are you sure you want to delete {{task.title}} ?"</h3>
                            
                            <input  type="submit" value="Delete Task" style="color: aliceblue;background-color: rgb(47, 19, 72);"></input></div>
                        </form>
                    </div>
                </div>



    </section>
    </main>
    </div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
    <!-- <script src="{% static 'js/index.js' %}"></script> -->
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
</body>



{% endblock %}
<!-- </body> -->

<!-- <extra js>-->
{% block extra_js %}{% endblock %}

core/templates/todo/task_list.html
{% extends 'base.html' %}
{% load static %}

<!-- <title>  -->
{% block title %} Todo App {% endblock %}
<!-- <extra css>-->
{% block extra_css %}{% endblock %}

<!-- <body> -->
{% block content %}






<body class="body">
    <div class="container">
        <div class="today"></div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3">
                <div class="add-control">
                    <div class="form-group has-feedback">
                        <form method="post" action="{% url 'todo:create_task' %}">
                            {% csrf_token %}

                            <input type="text" class="form-control" name="title" placeholder="✍️ Add task...">
                            <!-- <i class="fa fa-plus form-control-feedback add-btn"  title="Add item"></i> -->
                            <button type="submit" class=" form-control-feedback add-btn" title="Add item"
                                style="background-color: lightgray;align-content: center;color: rgb(255, 255, 255);font-size:x-small; padding: 0%; ">
                                <i class="fa fa-plus form-control-feedback add-btn"
                                    style="padding-left: 10%;align-content: center;" title="Add item"></i></button>

                        </form>
                    </div>
                </div>
                <p class="err text-danger text-center hidden"><i class="fa fa-warning"></i> Oops! Please, enter name
                    item</p>
                <p class="no-items text-muted text-center hidden"><i class="fa fa-ban"></i></p>
                <ul class="todo-list">
                    <ul class="todo-list ui-sortable">
                        {% for task in tasks %}
                        <li class="">
                            
                            {% if task.complete == True %}

                            <div class="checkbox" style="background-color: rgb(79, 47, 172);">
                                <a href="{% url 'todo:update_task' pk=task.id %}"><span class="close" style="margin-right: 22px ;width: 12px;
                                height: 16px;"><svg xmlns="http://www.w3.org/2000/svg" height="1em"
                                            viewBox="0 0 576 512">
                                            <path
                                                d="M402.6 83.2l90.2 90.2c3.8 3.8 3.8 10 0 13.8L274.4 405.6l-92.8 10.3c-12.4 1.4-22.9-9.1-21.5-21.5l10.3-92.8L388.8 83.2c3.8-3.8 10-3.8 13.8 0zm162-22.9l-48.8-48.8c-15.2-15.2-39.9-15.2-55.2 0l-35.4 35.4c-3.8 3.8-3.8 10 0 13.8l90.2 90.2c3.8 3.8 10 3.8 13.8 0l35.4-35.4c15.2-15.3 15.2-40 0-55.2zM384 346.2V448H64V128h229.8c3.2 0 6.2-1.3 8.5-3.5l40-40c7.6-7.6 2.2-20.5-8.5-20.5H48C21.5 64 0 85.5 0 112v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V306.2c0-10.7-12.9-16-20.5-8.5l-40 40c-2.2 2.3-3.5 5.3-3.5 8.5z" />
                                        </svg></span></a>
                                <a href="{% url 'todo:delete_task' pk=task.id %}"><span class="close"><i
                                            class="fa fa-times"></i></span></a>

                                <label style="background-color: rgb(79, 47, 172);">
                                    <!--<span class="checkbox-mask"><input type="checkbox"></span> -->
                                    <a href="{% url 'todo:complete_task' task.id %}"></a>
                                    <strike>{{task.title}}</strike>

                            {% else %}
                                    <div class="checkbox">
                                        <a href="{% url 'todo:update_task' pk=task.id %}"><span class="close" style="margin-right: 22px ;width: 12px;
                                        height: 16px;"><svg xmlns="http://www.w3.org/2000/svg" height="1em"
                                                    viewBox="0 0 576 512">
                                                    <path
                                                        d="M402.6 83.2l90.2 90.2c3.8 3.8 3.8 10 0 13.8L274.4 405.6l-92.8 10.3c-12.4 1.4-22.9-9.1-21.5-21.5l10.3-92.8L388.8 83.2c3.8-3.8 10-3.8 13.8 0zm162-22.9l-48.8-48.8c-15.2-15.2-39.9-15.2-55.2 0l-35.4 35.4c-3.8 3.8-3.8 10 0 13.8l90.2 90.2c3.8 3.8 10 3.8 13.8 0l35.4-35.4c15.2-15.3 15.2-40 0-55.2zM384 346.2V448H64V128h229.8c3.2 0 6.2-1.3 8.5-3.5l40-40c7.6-7.6 2.2-20.5-8.5-20.5H48C21.5 64 0 85.5 0 112v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V306.2c0-10.7-12.9-16-20.5-8.5l-40 40c-2.2 2.3-3.5 5.3-3.5 8.5z" />
                                                </svg></span></a>
                                        <a href="{% url 'todo:delete_task' pk=task.id %}"><span class="close"><i
                                                    class="fa fa-times"></i></span></a>

                                        <label>
                                            <!--<span class="checkbox-mask"><input type="checkbox"></span> -->
                                            <a href="{% url 'todo:complete_task' task.id %}"><span
                                                    class="checkbox-mask"><input type="checkbox"></span></a>
                                            <span>{{task}}</span>
                                            {% endif %}
                                        </label>

                                    </div>
                        </li>
                        {% endfor %}

                    </ul>
                </ul>
            </div>
        </div>
    </div>



    </section>
    </main>
    </div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
    <!-- <script src="js/index.js"></script> -->
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
</body>



{% if page_obj.has_other_pages %}
<!-- pagination -->
<div class="container">

    <div class="pagination p1">
        <ul>
            <h4>Pages</h4>

            <!-- previous and first page -->
            {% if current_page.number != 1 %}
            <a href="/?page={{previous_page}}">
                <li>
                    < </li>
            </a>

            {% if current_page.number != 2 %}
            <a href="/?page={{first_page}}">
                <li> First </li>
            </a>
            {% endif %}
            {% endif %}
            <!-- end -->

            <!-- pagination numbers -->
            {% for i in pages %}
            {% if page_obj.number == i %}
            <a class="is-active" href="/?page={{i}}">
                <li>{{i}}</li>
            </a>
            {% else %}
            <a href="/?page={{i}}">
                <li>{{i}}</li>
            </a>
            {% endif %}
            {% endfor %}
            <!-- end -->

            <!-- next and last page -->
            {% if current_page.number != next_page %}
            <a href="/?page={{next_page}}">
                <li>></li>
            </a>
            {% if last_page != 1 %}
            <a href="/?page={{last_page}}">
                <li> Last </li>
            </a>
            {% endif %}

            {% endif %}
            <!-- end -->

        </ul>
    </div>
</div>
{% endif %}


{% endblock %}
<!-- </body> -->

<!-- <extra js>-->
{% block extra_js %}{% endblock %}

core/templates/todo/task_update.html
{% extends 'base.html' %}
{% load static %}

<!-- <title>  -->
{% block title %} Edit Task {% endblock %}
<!-- <extra css>-->
{% block extra_css %}{% endblock %}

<!-- <body> -->
{% block content %}



<body class="body">
    <div class="container">
        <div class="today"></div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3">
                <div class="add-control">
                    <div class="form-group has-feedback">
                        <form method="POST" action="{% url 'todo:update_task' pk=task.id %}">
                            {% csrf_token %}

                            <input type="text" class="form-control" name="title" value="{{task.title}}" placeholder="✍️ Add task...">
                            
                            <button type="submit" class=" form-control-feedback add-btn" title="Add item"
                                style="background-color: lightgray;align-content: center;color: rgb(255, 255, 255);font-size:x-small; padding: 0%; ">
                                <i class="fa fa-plus form-control-feedback add-btn"
                                    style="padding-left: 10%;align-content: center;" title="Add item"></i></button>
                        </form>
                    </div>
                </div>
                <p class="err text-danger text-center hidden"><i class="fa fa-warning"></i> Oops! Please, enter name
                    item</p>



    </section>
    </main>
    </div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
    <!-- <script src="{% static 'js/index.js' %}"></script> -->
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
</body>





{% endblock %}
<!-- </body> -->

<!-- <extra js>-->
{% block extra_js %}{% endblock %}

core/templates/todo/weather.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather</title>
</head>
<body>
    <section class="vh-100" style="background-color: #f5f6f7;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-10 col-lg-8 col-xl-6">
      
              <div class="card bg-dark text-white" style="border-radius: 40px;">
                <div class="bg-image" style="border-radius: 35px;">
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-weather/draw1.webp"
                    class="card-img" alt="weather" />
                  <div class="mask" style="background-color: rgba(190, 216, 232, .5);"></div>
                </div>
                <div class="card-img-overlay text-dark p-5">
                  <h4 class="mb-0">{{weather_api.name}}, {{weather_api.sys.country}}</h4>
                  <p class="display-2 my-3">{{weather_api.main.temp}}°C</p>
                  <p class="mb-2">Feels Like: <strong>{{weather_api.main.feels_like}} °C</strong></p>
                  <h5>{{weather_api.weather.description}}</h5>
                </div>
              </div>
      
            </div>
          </div>
        </div>
      </section>
</body>
</html>